'use client';

import { createAuthClient } from '@erp/auth-client';

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001/api/v1';

export const authClient = createAuthClient({
  baseUrl: API_URL,
  storageKeyPrefix: 'gestion',
  onUnauthenticated: () => {
    if (typeof window !== 'undefined' && !window.location.pathname.startsWith('/login')) {
      window.location.href = '/login';
    }
  },
});

export const {
  useMe,
  useLogin,
  useLogout,
  useLogoutAll,
  useChangePassword,
  useForgotPassword,
  useResetPassword,
  useCompanies,
  useActiveCompany,
  useBranches,
  useActiveBranch,
  useActiveBranchId,
  usePermissions,
  useRoles,
  useRole,
  usePermissionCatalog,
  useCreateRole,
  useUpdateRole,
  useDeleteRole,
  useReplaceRolePermissions,
  useCompanyUsers,
  useUserRoles,
  useAssignRole,
  useRemoveRoleAssignment,
  useAuditLog,
  useAuditLogDetail,
  useCustomers,
  useCustomer,
  useCustomerHistory,
  useCustomerLookup,
  useCreateCustomer,
  useUpdateCustomer,
  useDeactivateCustomer,
  useReactivateCustomer,
  useAddCustomerAddress,
  useUpdateCustomerAddress,
  useRemoveCustomerAddress,
  useAddCustomerContact,
  useUpdateCustomerContact,
  useRemoveCustomerContact,
  useCustomerCategories,
  useCreateCustomerCategory,
  useUpdateCustomerCategory,
  useProducts,
  useProduct,
  useProductHistory,
  useProductLookup,
  useCreateProduct,
  useUpdateProduct,
  useDeactivateProduct,
  useReactivateProduct,
  useAddProductVariant,
  useUpdateProductVariant,
  useDeactivateProductVariant,
  useReactivateProductVariant,
  useAddProductCode,
  useUpdateProductCode,
  useRemoveProductCode,
  useProductCategories,
  useCreateProductCategory,
  useUpdateProductCategory,
  useDeactivateProductCategory,
  useBrands,
  useCreateBrand,
  useUpdateBrand,
  useDeactivateBrand,
  useUnits,
  useCreateUnit,
  useUpdateUnit,
  useDeactivateUnit,
  useWarehouses,
  useWarehouse,
  useCreateWarehouse,
  useUpdateWarehouse,
  useDeactivateWarehouse,
  useReactivateWarehouse,
  useStock,
  useProductStock,
  useVariantStock,
  useInventoryLookup,
  useMovements,
  useMovement,
  useCreateInitialBalance,
  useStockAdjustments,
  useStockAdjustment,
  useCreateStockAdjustment,
  useUpdateStockAdjustment,
  useConfirmStockAdjustment,
  useCancelStockAdjustment,
  useCurrencies,
  usePriceLists,
  usePriceList,
  useCreatePriceList,
  useUpdatePriceList,
  useDeactivatePriceList,
  useReactivatePriceList,
  usePriceListHistory,
  usePriceListItems,
  useSetPrice,
  useSetPrices,
  usePreviewBulkAdjust,
  useConfirmBulkAdjust,
  usePriceHistory,
  usePriceLookup,
  useLookupPricesBatch,
  useProductPrices,
  useSales,
  useSale,
  useCreateSale,
  useUpdateSale,
  useConfirmSale,
  useCancelSale,
  useDashboardSummary,
  useRealtimeSync,
} = authClient;
