/**
 * Framework-agnostic mirrors of the Prisma enums in apps/api.
 * Kept here (rather than importing the generated Prisma client) so that
 * apps/web can use the same string literal unions without depending on
 * backend-only generated code.
 */

export const TenantStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
} as const;
export type TenantStatus = (typeof TenantStatus)[keyof typeof TenantStatus];

export const CompanyStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
} as const;
export type CompanyStatus = (typeof CompanyStatus)[keyof typeof CompanyStatus];

export const BranchStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
export type BranchStatus = (typeof BranchStatus)[keyof typeof BranchStatus];

export const UserStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  BLOCKED: 'BLOCKED',
  PENDING: 'PENDING',
} as const;
export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus];

/** See docs/customers.md — Argentina-oriented but not exhaustive; OTHER covers the rest. */
export const CustomerType = {
  COMPANY: 'COMPANY',
  INDIVIDUAL: 'INDIVIDUAL',
  FINAL_CONSUMER: 'FINAL_CONSUMER',
  FOREIGN: 'FOREIGN',
} as const;
export type CustomerType = (typeof CustomerType)[keyof typeof CustomerType];

export const CustomerStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
export type CustomerStatus = (typeof CustomerStatus)[keyof typeof CustomerStatus];

export const CustomerDocumentType = {
  CUIT: 'CUIT',
  CUIL: 'CUIL',
  DNI: 'DNI',
  PASSPORT: 'PASSPORT',
  OTHER: 'OTHER',
} as const;
export type CustomerDocumentType = (typeof CustomerDocumentType)[keyof typeof CustomerDocumentType];

export const CustomerTaxCondition = {
  RESPONSABLE_INSCRIPTO: 'RESPONSABLE_INSCRIPTO',
  MONOTRIBUTO: 'MONOTRIBUTO',
  EXENTO: 'EXENTO',
  CONSUMIDOR_FINAL: 'CONSUMIDOR_FINAL',
  NO_RESPONSABLE: 'NO_RESPONSABLE',
  EXTERIOR: 'EXTERIOR',
  OTHER: 'OTHER',
} as const;
export type CustomerTaxCondition = (typeof CustomerTaxCondition)[keyof typeof CustomerTaxCondition];

export const CustomerAddressType = {
  FISCAL: 'FISCAL',
  BILLING: 'BILLING',
  SHIPPING: 'SHIPPING',
  OTHER: 'OTHER',
} as const;
export type CustomerAddressType = (typeof CustomerAddressType)[keyof typeof CustomerAddressType];

/** See docs/products.md. */
export const ProductType = {
  PRODUCT: 'PRODUCT',
  SERVICE: 'SERVICE',
  KIT: 'KIT',
  MANUFACTURED: 'MANUFACTURED',
} as const;
export type ProductType = (typeof ProductType)[keyof typeof ProductType];

export const ProductStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
export type ProductStatus = (typeof ProductStatus)[keyof typeof ProductStatus];

export const ProductCodeType = {
  BARCODE: 'BARCODE',
  SUPPLIER: 'SUPPLIER',
  INTERNAL: 'INTERNAL',
  MARKETPLACE: 'MARKETPLACE',
  OTHER: 'OTHER',
} as const;
export type ProductCodeType = (typeof ProductCodeType)[keyof typeof ProductCodeType];

/** See docs/inventory.md. */
export const WarehouseStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
export type WarehouseStatus = (typeof WarehouseStatus)[keyof typeof WarehouseStatus];

/**
 * Signed-quantity convention per type — see docs/inventory.md. Only
 * INITIAL_BALANCE/ADJUSTMENT_IN/ADJUSTMENT_OUT are actually generated by
 * this task; the rest exist for forward compatibility.
 */
export const MovementType = {
  INITIAL_BALANCE: 'INITIAL_BALANCE',
  ADJUSTMENT_IN: 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT: 'ADJUSTMENT_OUT',
  TRANSFER_IN: 'TRANSFER_IN',
  TRANSFER_OUT: 'TRANSFER_OUT',
  PURCHASE: 'PURCHASE',
  PURCHASE_RETURN: 'PURCHASE_RETURN',
  SALE: 'SALE',
  SALE_RETURN: 'SALE_RETURN',
  DELIVERY: 'DELIVERY',
  PRODUCTION_IN: 'PRODUCTION_IN',
  PRODUCTION_OUT: 'PRODUCTION_OUT',
} as const;
export type MovementType = (typeof MovementType)[keyof typeof MovementType];

/** See docs/inventory.md — `quantity` on StockReservation is the CURRENT outstanding amount, not the original request. */
export const ReservationStatus = {
  ACTIVE: 'ACTIVE',
  PARTIALLY_CONSUMED: 'PARTIALLY_CONSUMED',
  CONSUMED: 'CONSUMED',
  RELEASED: 'RELEASED',
  EXPIRED: 'EXPIRED',
} as const;
export type ReservationStatus = (typeof ReservationStatus)[keyof typeof ReservationStatus];

export const StockAdjustmentStatus = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
} as const;
export type StockAdjustmentStatus = (typeof StockAdjustmentStatus)[keyof typeof StockAdjustmentStatus];

/** See docs/pricing.md. FIXED = explicit PriceListItem rows; DERIVED = computed at read time from basePriceListId + adjustment, never materialized. */
export const PricingMode = {
  FIXED: 'FIXED',
  DERIVED: 'DERIVED',
} as const;
export type PricingMode = (typeof PricingMode)[keyof typeof PricingMode];

/** Direction is explicit in the type (never a signed adjustmentValue) — see docs/pricing.md. */
export const AdjustmentType = {
  PERCENTAGE_INCREASE: 'PERCENTAGE_INCREASE',
  PERCENTAGE_DECREASE: 'PERCENTAGE_DECREASE',
  FIXED_AMOUNT_INCREASE: 'FIXED_AMOUNT_INCREASE',
  FIXED_AMOUNT_DECREASE: 'FIXED_AMOUNT_DECREASE',
} as const;
export type AdjustmentType = (typeof AdjustmentType)[keyof typeof AdjustmentType];

/** Discriminates a PriceHistory row's origin — see docs/pricing.md. */
export const PriceChangeType = {
  INITIAL: 'INITIAL',
  MANUAL: 'MANUAL',
  BULK_ADJUSTMENT: 'BULK_ADJUSTMENT',
} as const;
export type PriceChangeType = (typeof PriceChangeType)[keyof typeof PriceChangeType];

/** Stable, closed catalog — see docs/audit-architecture.md. Entity type plus metadata provides the rest of the context, so this stays small. */
export const AuditAction = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  ACTIVATE: 'ACTIVATE',
  DEACTIVATE: 'DEACTIVATE',
  ASSIGN: 'ASSIGN',
  UNASSIGN: 'UNASSIGN',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  CANCEL: 'CANCEL',
  VOID: 'VOID',
  CONFIRM: 'CONFIRM',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  PASSWORD_RESET: 'PASSWORD_RESET',
  SESSION_REVOKE: 'SESSION_REVOKE',
  PERMISSIONS_CHANGE: 'PERMISSIONS_CHANGE',
  EXPORT: 'EXPORT',
} as const;
export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];

/** Only one document type in this task — an internal sale, not a fiscal invoice. See docs/sales.md. */
export const SalesDocumentType = {
  SALE: 'SALE',
} as const;
export type SalesDocumentType = (typeof SalesDocumentType)[keyof typeof SalesDocumentType];

/** See docs/sales.md for the exact state machine — CONFIRMED and CANCELLED are both terminal. */
export const SalesDocumentStatus = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
} as const;
export type SalesDocumentStatus = (typeof SalesDocumentStatus)[keyof typeof SalesDocumentStatus];
